### ISSUE TITLE
Does it support Elgama or Gama electricity meter? 

### ISSUE THREAD

**Issue by flyzet-prog** [geduxas/esphome-dsmr-eso#1]
Hi dev. Does it support Elgama or [Gama](https://www.elgama.eu/gama-100-en) electricity meter(They are also Lithuanian)? Would be much appreciated for your response.

**Comment by geduxas** [comment]
> Hi dev. Does it support Elgama or [Gama](https://www.elgama.eu/gama-100-en) electricity meter(They are also Lithuanian)? Would be much appreciated for your response.

Unfortunately no, it's for new ESO smart meters, Sagemcom TS211 (3 phase) and XS211(1 phase) meters which support's P1 interface.

Truly don't know about Elgama, but i think protocol and OBIS via optical sensor could be similar. 

And optical sensor for elgama made meters should standart.

**Comment by flyzet-prog** [comment]
Thank you for replay!
