### ISSUE TITLE
Issue after ESO P1 upgrade

### ISSUE THREAD

**Issue by sepetuks** [geduxas/esphome-dsmr-eso#2]
After latest ESO P1 upgrade I have invalid unit error:
![image](https://github.com/geduxas/esphome-dsmr-eso/assets/60431795/732e821e-07eb-4ce6-b426-48caf1ef951e)

**Comment by geduxas** [comment]
> After latest ESO P1 upgrade I have invalid unit error: ![image](https://private-user-images.githubusercontent.com/60431795/328935251-732e821e-07eb-4ce6-b426-48caf1ef951e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODE5NzcsIm5iZiI6MTcxNTE4MTY3NywicGF0aCI6Ii82MDQzMTc5NS8zMjg5MzUyNTEtNzMyZTgyMWUtMDdlYi00Y2U2LWI0MjYtNDhjYWYxZWY5NTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOThmMzQ0OWNkNDQ3MmIwNDYzNmVhYTg5YzU0OGEwY2MzMzcyYjIyZThkYzZlZGIwNTEyMjQ3YjFmZDU3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2qOoK4IvcQsS91jegHyi0Z3J-TtqwyjFuP0MUODJq0c)

Have you tried update? Recently i have made update to my repo

**Comment by sepetuks** [comment]
I think (I am no so good in all this topic) this is part of the parser topic.
I see you have separate parser specified: 
    `cg.add_library("https://github.com/geduxas/arduino-dsmr.git","0.8.0")`
as ESO changed from kV to V I think it still expects kV.

Latest data from ESO meter:
![image](https://github.com/geduxas/esphome-dsmr-eso/assets/60431795/ba683e4d-d250-4c10-82f9-22463f9ba0fa)

**Comment by geduxas** [comment]
From screenshot it's seam's old build. Sorry I don't mantain version upgrade, just made yaml to grab latest source from my repo.. 
so just clean your build in esphome and rebuild.

**Comment by sepetuks** [comment]
thanks for hint.
Clean old build files helped/
![image](https://github.com/geduxas/esphome-dsmr-eso/assets/60431795/79b60ca3-d9ca-427a-a8db-8cd9f36d0bad)

**Comment by geduxas** [comment]
made some changes in main config, now it's possible to change config acording profile:

```
packages:
  esodsmr: github://geduxas/esphome-dsmr-eso/p1_standard.yaml@main # p1_standard.yaml; p1_extended.yaml; p1_max.yaml
```
