### ISSUE TITLE
Profilis : Maksimalus

### ISSUE THREAD

**Issue by Ginetas** [geduxas/esphome-dsmr-eso#4]
Sveikas, 
Gal numatęs maksimaliam profiliui ?

**Comment by geduxas** [comment]
Sveikas, kolkas viskas yra kas buvo prieš ESO FW naujinimą, dar papildomai pridėjau tekstinius laukus, 
žinoma ne visi OBIS registrai yra sukonfiguruoti per ESPHome YAML, tačiau DSMR'e yra visi. Žadu padaryti dinamini config kur pagal profilius atvaizduos telemetrija, bet tam reikiarasti laisvo laiko :) 

Šiuo metu pagrindiniai elementai yra.

**Comment by geduxas** [comment]
> Sveikas, Gal numatęs maksimaliam profiliui ?

Padariau pakeitimu, dabar reiktu pasikeisti yaml pagal profilį, mistika su ESPHome yra ta kad užsikešuoja gito konfigus, ir kas kažkiek laiko atsinaujina.. man pačiam teko priverstinai išvalyti viską. 

reikia pakeisti:
```
packages:
  esodsmr: github://geduxas/esphome-dsmr-eso/p1_standard.yaml@main # p1_standard.yaml; p1_extended.yaml; p1_max.yaml
```
