### ISSUE TITLE
ota updates neveikia

### ISSUE THREAD

**Issue by mogim0gi** [geduxas/esphome-dsmr-eso#6]
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/slimmelezer.yaml...
INFO Updating https://github.com/geduxas/esphome-dsmr-eso.git@main
Failed config

ota.unknown: [source /data/packages/50047a6c/esp8266.yaml:39]
  
  'ota' requires a 'platform' key but it was not specified.
  password: !secret ota_password
  
  manau cia klaida :
  
  ota:
 - platform: esphome
   password: "xxxxxxxxxxxxxxxx"
   num_attempts: 3
   safe_mode: no

**Comment by geduxas** [comment]
Gal su 2024.6.1 kas pasikeitė, dar nebandžiau naujinti. O dėl OTA rakto pagal esphome galima jį bendrą turėti secrets.yaml faile..

**Comment by mogim0gi** [comment]
jo, panasu kad yra breaking changes :
https://next.esphome.io/components/ota

truksta -platform: esphome
 dalies manau

**Comment by geduxas** [comment]
Atnaujinau, dabar jau turi kompiliuotis :)

**Comment by mogim0gi** [comment]
blogas update, truksta "-" :

```
ota: [source /data/packages/50047a6c/esp8266.yaml:39]
  
  [platform] is an invalid option for [ota]. Please check the indentation.
  platform: esphome
  password: !secret ota_password
```
Turetu buti taip:

```
ota:
  - platform: esphome
    password: !secret ota_password
```

**Comment by geduxas** [comment]
Keista, lokaliai susikompiliavo be problemų, pridėjau -

**Comment by mogim0gi** [comment]
dabar ok, aciu :)
